#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#


export JAVA_HOME="$(/usr/libexec/java_home)"

key=$HOME/.aws/pk-florianduetsch.pem
if [[ -f $key ]]; then export EC2_PRIVATE_KEY=$key; fi
cert=$HOME/.aws/cert-florianduetsch.pem
if [[ -f $cert ]]; then export EC2_CERT=$cert; fi

export AWS_AUTO_SCALING_HOME="/usr/local/Library/LinkedKegs/auto-scaling/jars"
export EC2_HOME="/usr/local/Library/LinkedKegs/ec2-api-tools/jars"
export AWS_ACCESS_KEY_ID=`cat "$HOME"/.aws/access_key_id`
export AWS_SECRET_ACCESS_KEY=`cat "$HOME"/.aws/secret_access_key`
export EC2_URL="https://ec2.eu-west-1.amazonaws.com"
