#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...


alias subl_nowait='subl &!'

# TODO: Remove
source ~/.git-flow-completion.zsh

# TODO?
# if [[ "$TERM" != "screen-256color" ]]
# then
#   tmux new-session
#   exit
# fi


alias ag='noglob ag --hidden'
alias agi='noglob ag --hidden --ignore-case'
alias be='bundle exec'
alias bo='VISUAL=subl bundle open'
