#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Read history from file aka. import commands from other shells
#
# http://zsh.sourceforge.net/Doc/Release/Options.html#History
#   If you find that you want more control over when commands get imported,
#   you may wish to turn SHARE_HISTORY off, INC_APPEND_HISTORY on, and then
#   manually import commands whenever you need them using ‘fc -RI’.
unsetopt SHARE_HISTORY
alias read_history='fc -RI'
alias rh=read_history

# if [[ "$TERM" != "screen-256color" ]]
# then
#   tmux new-session
#   exit
# fi

alias txn='tmux new-session'
alias subl_nowait='subl &!'
alias ag='noglob ag --hidden'
alias agi='noglob ag --hidden --ignore-case'
alias todo_flo='ag "TODO\sFlo(?!2)"'
alias todo='ag "TODO(?! Prio [23])"'

alias be='bundle exec'
alias bo='VISUAL=subl_nowait bundle open'
alias bi='bundle install -j4'
alias bil='bundle install -j4 --local'

alias otrs_spool='ssh otrs.nwwo.de ls /opt/otrs/var/spool'

# http://www.saturnflyer.com/blog/jim/2013/03/15/searching-through-your-bundled-gems/
function ag_gem() {
  ag $1 `bundle show --paths`
}

alias showFiles='defaults write com.apple.finder AppleShowAllFiles YES; killall Finder /System/Library/CoreServices/Finder.app'
alias hideFiles='defaults write com.apple.finder AppleShowAllFiles NO; killall Finder /System/Library/CoreServices/Finder.app'

browse() { open $(eval ${1}) }

alias http_dir='ruby -run -e httpd . --port=8080'

alias topswap='getswap | egrep -v "Swap used: 0" | sort -n -k 5'

# Git
alias branch_current='git rev-parse --abbrev-ref HEAD'
alias branch_oldest_ancestor='/usr/bin/diff -u <(git rev-list --first-parent master) <(git rev-list --first-parent HEAD) | sed -ne "s/^ //p" | head -1'
alias branch_log='git log $(branch_oldest_ancestor)..HEAD'
alias branch_diff='git diff $(branch_oldest_ancestor)..HEAD'
alias branch_files='git diff $(branch_oldest_ancestor)..HEAD --diff-filter=ACMR --name-only --oneline'

# Bitbucket
alias bitbucket_repo_url='echo https://$(git remote -v | grep -oh "bitbucket.org[:/][^ .]\+" | head -1 | sed "s/:/\//")'
alias bitbucket_review_url='echo $(bitbucket_repo_url)/branches/compare/$(branch_current)..$(branch_oldest_ancestor)'

# Redmine
alias redmine_url='echo http://redmine.nwwo.de/issues/$(branch_current | grep -oh "^[0-9]\+")'

# Rubocop
alias branch_rubocop="branch_files | grep '\.rb$' | xargs rubocop"

# Shortcuts
alias bbb='browse bitbucket_repo_url'
alias bbbr='browse bitbucket_review_url'
alias bred='browse redmine_url'
