#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Read history from file aka. import commands from other shells
#
# http://zsh.sourceforge.net/Doc/Release/Options.html#History
#   If you find that you want more control over when commands get imported,
#   you may wish to turn SHARE_HISTORY off, INC_APPEND_HISTORY on, and then
#   manually import commands whenever you need them using ‘fc -RI’.
unsetopt SHARE_HISTORY
alias read_history='fc -RI'
alias rh=read_history

# if [[ "$TERM" != "screen-256color" ]]
# then
#   tmux new-session
#   exit
# fi

alias txn='tmux new-session'
alias subl_nowait='subl &!'
alias ag='noglob ag --hidden'
alias agi='noglob ag --hidden --ignore-case'
alias todo_flo='ag "TODO\sFlo:"'
alias todo='ag "TODO((?!Prio).)*:"'

alias be='bundle exec'
alias bo='VISUAL=subl_nowait bundle open'
alias bi='bundle install -j4'
alias bil='bundle install -j4 --local'

# http://www.saturnflyer.com/blog/jim/2013/03/15/searching-through-your-bundled-gems/
function ag_gem() {
  ag $1 `bundle show --paths`
}

