set guioptions-=T                 " Remove toolbar
set guioptions-=r                 " Remove right scrollbar
set lines=25 columns=85           " UI size
set guifont=Source\ Code\ Pro:h16 " font size

