source ~/.vim/plugins.vim
source ~/.vim/filetypes.vim
source ~/.vim/key_mappings.vim
source ~/.vim/syntastic.vim

" Appearance
set background=dark
colorscheme PaperColor
set colorcolumn=81 " show a limiting column after 80 characters
set number " show line numbers

set nowrap " do not wrap lines

" TODO: does not work yet inside tmux
set title " show filename in window title

set hidden " hide a buffer instead of closing it
           " => switch buffers even with the actual unsaved

" TODO: really write swap files?

" tab: show invisible tabs
" trail: show trailing whitespace
" precedes, extends: show whether lines are too long to be completely visible
set list listchars=tab:»·,trail:·,precedes:<,extends:>

" Indentation http://vim.wikia.com/wiki/Indenting_source_code
set expandtab " expand tab key presses to spaces
set softtabstop=2 " tabstops are two spaces
set shiftwidth=2 " width of autoindentation

" Searching
set hlsearch " highlight search results
set incsearch " immediately start searching
set ignorecase " ignore case when searching
set smartcase " only ignore case when search string does not contain upper
              " case characters

" Mouse
set mouse=a " enable mouse in all modes
set ttymouse=xterm2 " resize splits with mouse when inside tmux session

set laststatus=2
let g:airline#extensions#tabline#enabled=1
let g:airline_powerline_fonts=1

" Strip trailing whitespace when saving files
" TODO Prio 2: "silent!" ?
autocmd BufWritePre * :%s/\s\+$//e
