" :help <foobar> for explanations

source ~/.vim/plugins.vim
source ~/.vim/filetypes.vim
source ~/.vim/key_mappings.vim


" enable true-color output
" TODO: Needed? Working?
" set termguicolors
" let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
" let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"

" TODO: Check out features intensively
" https://github.com/rakr/vim-one
colorscheme one
set background=light

set colorcolumn=81
set textwidth=80
set number
set cursorline
set nowrap
set fillchars+=vert:│ " nicer vertical line
set backspace=indent,eol,start " backspace as expected

" TODO: does not work yet inside tmux
" https://stackoverflow.com/questions/15123477/tmux-tabs-with-name-of-file-open-in-vim
set title

set hidden " hide a buffer instead of closing it
           " ⇒ switch buffers even with the actual unsaved
set autoread
set list
set listchars=tab:▸·,trail:·,precedes:◅,extends:▻,nbsp:•

" Indentation http://vim.wikia.com/wiki/Indenting_source_code
set expandtab " expand tab key presses to spaces
set softtabstop=2 " tabstops are two spaces
set shiftwidth=2 " width of autoindentation

" Searching
set hlsearch
set incsearch
set ignorecase
set smartcase

" Mouse
set mouse=a
set ttymouse=xterm2 " resize splits with mouse when inside tmux session

" ALE
" TODO: Configure nicer appearance
let g:ale_linters = { 'ruby': ['ruby', 'rubocop'] }

" Airline
let g:airline_powerline_fonts=1
let g:airline#parts#ffenc#skip_expected_string='utf-8[unix]'
let g:airline_skip_empty_sections = 1
" let g:airline#extensions#ale#enabled = 1 " TODO: nicer appearence for ALE
set noshowmode " airline now shows the active mode
autocmd WinLeave * :let w:airline_render_right=0

" vim-gitgutter
set updatetime=100 " show the git changes earlier

let test#strategy = 'vimterminal'

" NERDTree
let g:NERDTreeMouseMode=2
let g:NERDTreeAutoDeleteBuffer=1
let g:NERDTreeQuitOnOpen=1

" Open a NERDTree automatically when vim starts up if no files were specified
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif

" Close Vim if the only window left open is a NERDTree
autocmd BufEnter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

" Strip trailing whitespace when saving files
autocmd BufWritePre * :%s/\s\+$//e

" https://github.com/junegunn/fzf.vim#global-options
let g:fzf_colors =
\ { 'fg':      ['fg', 'Normal'],
  \ 'bg':      ['bg', 'Normal'],
  \ 'hl':      ['fg', 'Comment'],
  \ 'fg+':     ['fg', 'CursorLine', 'CursorColumn', 'Normal'],
  \ 'bg+':     ['bg', 'CursorLine', 'CursorColumn'],
  \ 'hl+':     ['fg', 'Statement'],
  \ 'info':    ['fg', 'PreProc'],
  \ 'border':  ['fg', 'Ignore'],
  \ 'prompt':  ['fg', 'Conditional'],
  \ 'pointer': ['fg', 'Exception'],
  \ 'marker':  ['fg', 'Keyword'],
  \ 'spinner': ['fg', 'Label'],
  \ 'header':  ['fg', 'Comment'] }
