# Die Projektverzeichnisse überschreiben diese Versionen.
[tools]
"aqua:hashicorp/terraform" = "latest"

# TODO: Bumpen
node = "22.13.0"
ruby = "4.0.6"

[settings]
idiomatic_version_file_enable_tools = ["ruby"]

[settings.ruby]
compile = false
